WSJoyStick.onKey(KEY.F, function () {
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(523, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(523, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(988, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    WSJoyStick.PlayMusic(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
})
WSJoyStick.JoyStickInit()
basic.forever(function () {
	
})
